eureka:
  instance:
    #hostname: registry
#    ip-address: 192.168.1.200
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@192.168.1.200:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

spring:
  rabbitmq:
    host: 192.168.1.200
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"

authserver:
    #hostname: auth-service
    port: 5000
    contextPath: /uaa

security:
  oauth2:
    resource:
      user-info-uri: http://192.168.1.200:8060${authserver.contextPath}/current
      #user-info-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/current
