server:
  port: 8060

management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

zuul:
  ignoredServices: '*'
  routes:
    auth-service:
      path: /uaa/**
      serviceId: auth-service
      sensitiveHeaders: '*'
    svca-service:
      path: /a/**
      sensitiveHeaders: '*'